development:
  adapter: postgresql
  encoding: utf8
  database: bewd_app_development
  pool: 5


test: &TEST
  adapter: postgresql
  encoding: utf8
  database: bewd_app_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: bewd_app_production
  pool: 5
